/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingexamples;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;

/**
 *
 * @author Producer
 */
public class EventExample extends javax.swing.JFrame{

    /**
     * Creates new form EventExample
     */
    public EventExample() {
        initComponents();
        setSize(500,500);
        
    }
  
    private Color randomColor()
    {
        Random num = new Random();
        int randCol = num.nextInt(9) + 1;
        switch(randCol)
        {
            case 1: 
                return Color.yellow;
            case 2: 
                return Color.red;
            case 3:
                return Color.blue;
            case 4: 
                return Color.green;
            case 5:
                return Color.orange;
            case 6: 
                return Color.cyan;
            case 7:
                return Color.pink;
            case 8: 
                return Color.magenta;
            case 9: 
                return Color.white;
            default:
                return Color.black;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Random Color");
        setSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        jButton1.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton1.setText("1");
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton2.setText("2");
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton3.setText("3");
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton4.setText("4");
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton5.setText("5");
        jPanel1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton6.setText("6");
        jPanel1.add(jButton6);

        jButton7.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton7.setText("7");
        jPanel1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton8.setText("8");
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        jButton9.setText("9");
        jPanel1.add(jButton9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
